export const requireInfoData = [
  {
    columnNum: 6,
    label: "First name",
    fieldName: "firstName",
    type: "text",
    regex_check_type: "string",
    placeholder: "John",
    isRequire: true,
  },
  {
    columnNum: 6,
    label: "Last name",
    fieldName: "lastName",
    type: "text",
    regex_check_type: "string",
    placeholder: "Snow",
    isRequire: true,
  },
  {
    columnNum: 6,
    label: "Phone number",
    fieldName: "phoneNumber",
    type: "text",
    regex_check_type: "string",
    placeholder: "0123 456 78",
    isRequire: true,
  },
  {
    columnNum: 6,
    label: "Email",
    fieldName: "email",
    type: "text",
    regex_check_type: "email",
    placeholder: "JohnSnow@gmail.com",
    isRequire: true,
  },

  {
    columnNum: 12,
    label: "Address",
    fieldName: "address",
    type: "text",
    regex_check_type: "string",
    placeholder: "Street ... United Kingdom (UK)",
    isRequire: true,
  },
  {
    columnNum: 12,
    label: "Order notes",
    fieldName: "note",
    type: "text",
    regex_check_type: "string",
    placeholder: "Anything else we need to know about your order!",
    isRequire: false,
  },
];
