export const DISPLAY_CART_MODAL = "DISPLAY_CART_MODAL";
// * CART LIST
export const SET_CART_LIST = "SET_CART_LIST";
// * CART ITEM
export const SET_DEFAULT_CART_ITEM = "SET_DEFAULT_CART_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
